settings:
  title: 'Status Page'
  url: 'https://status.ladbiblegroup.com' # used for Slack messages
  logo: logo.svg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www.ladbible.com # unique identifier
    name: LADbible
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.ladbible.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: www.sportbible.com
    name: SPORTbible
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.sportbible.com/'
    method: GET
    expectStatus: 200

  - id: www.tyla.com
    name: Tyla
    url: 'https://www.tyla.com/'
    method: GET
    expectStatus: 200

  - id: www.gamingbible.com
    name: GAMINGbible
    url: 'https://www.gamingbible.com/'
    method: GET
    expectStatus: 200

  - id: www.unilad.com
    name: UNILAD
    url: 'https://www.unilad.com/'
    method: GET
    expectStatus: 200
